### ISSUE TITLE
Doesn't show up in the UI at all

### ISSUE THREAD

**Issue by cmmh** [Adorkable/node-red-contrib-ui-led#12]
No luck getting it to actually show up in the UI.  Even pasting the example and, as a result, having it create new subflows, still doesn't have it showing up in the UI.   Currently on 0.17.5 for node-red

**Comment by cmmh** [comment]
I upgraded node-red to 0.19.5 and it is working now.

**Comment by yoiang** [comment]
Great to hear! Did you save off the error somewhere? Can look into potentially making the library more version robust.
