### ISSUE TITLE
Also a way to "reset" the LED to the "no data received" state.

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#15]
I appreciate the LED.

The only thing I would like to see is a way to put it back to the "I have not received anything yet" state.

I am using it as an indicator and though maybe a FULL DEPLOY would be better.....
It would be nice if something could be injected to reset to to the blank state/mode.

**Comment by yoiang** [comment]
I may include something similar in the custom statuses (#2), where if a payload doesn't match any of the defined states it will "turn off" ie. go back to blank. Is this what you were thinking?

**Comment by Just-another-pleb** [comment]
*I may include something similar in the custom statuses (#2
<https://github.com/Adorkable/node-red-contrib-ui-led/issues/2>), where if
a payload doesn't match any of the defined states it will "turn off" ie. go
back to blank.*

Yes.

**Comment by yoiang** [comment]
Implemented in [0.2.0](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.2.0)!

**Comment by Just-another-pleb** [comment]
Thanks, but.....

I just installed it and the documentation doesn't explain how to "reset"
the LED.

Shall look on the web page to see if there is any info there.

**Comment by yoiang** [comment]
I updated the documentation for how to, if one sends any value without a color associated it is "reset".
