### ISSUE TITLE
LED always shows grey

### ISSUE THREAD

**Issue by colinl** [Adorkable/node-red-contrib-ui-led#16]
I can't get the node to show anything other than grey.
I have configured a simple flow with two inject nodes injecting boolean true and false into the led node and nothing happens when I do the inject.  Here is the flow:
```
[{"id":"6d4c5778.575b6","type":"inject","z":"514a90a5.c7bae8","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":174,"y":517,"wires":[["a5be5c13.23cc"]]},{"id":"c4a9d112.426b18","type":"inject","z":"514a90a5.c7bae8","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":174,"y":557,"wires":[["a5be5c13.23cc"]]},{"id":"a5be5c13.23cc","type":"ui_led","z":"514a90a5.c7bae8","group":"536f7750.317da8","order":3,"label":"LED","name":"","x":404.5,"y":540,"wires":[]},{"id":"536f7750.317da8","type":"ui_group","z":"","name":"Default","tab":"cefe4a16.8f56d8","disp":false,"width":"12","collapse":false},{"id":"cefe4a16.8f56d8","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]
```
Running on Ubuntu 18.10 the node red log shows nothing unusual on startup.  Any suggestions will be gratefully received.
```
Welcome to Node-RED
===================
2 Feb 15:51:31 - [info] Node-RED version: v0.19.5
2 Feb 15:51:31 - [info] Node.js  version: v10.15.1
2 Feb 15:51:31 - [info] Linux 4.18.0-13-generic x64 LE
2 Feb 15:51:32 - [info] Loading palette nodes
2 Feb 15:51:33 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
2 Feb 15:51:33 - [warn] rpi-gpio : Cannot find Pi RPi.GPIO python library
2 Feb 15:51:34 - [info] Dashboard version 2.13.2 started at /ui
2 Feb 15:51:34 - [info] Settings file  : /home/me/.node-red/settings.js
2 Feb 15:51:34 - [info] HTTP Static    : /home/me/.node-red/static
2 Feb 15:51:34 - [info] Context store  : 'default' [module=memory]
2 Feb 15:51:34 - [info] User directory : /home/me/.node-red
2 Feb 15:51:34 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Feb 15:51:34 - [info] Flows file     : /home/me/.node-red/flows_tigger.json
2 Feb 15:51:34 - [info] Server now running at http://127.0.0.1:1880/
2 Feb 15:51:34 - [info] Starting flows
2 Feb 15:51:34 - [info] Started flows
```

**Comment by colinl** [comment]
It seems this is not a problem with this node, as I have problems with other contrib ui widgets.  Also it is specific to one profile with my browser so I am closing the issue.

**Comment by yoiang** [comment]
Ah gotcha, thank you for the update :) where you able to resolve the issue or find the root?

**Comment by colinl** [comment]
Not solved so far. It is very odd, with the debugger I can see that, in the server, it gets as far as passing the widget setup to angular, but in the client initController is never called.  Other built-in dashboard nodes work ok though, so there must be a difference in the interface between node-red and angular between the two. More investigation is required.  I see apparently the same issue with the ui_lists contrib widget too.  I will post back here if I manage to diagnose it further.

**Comment by yoiang** [comment]
Great :)

If you haven't already it might be a good thing to also report and track in the [Node-RED Github](https://github.com/node-red/node-red/issues)!

**Comment by colinl** [comment]
It has been discussed on the node-red discourse forum.  As yet it is not clear whether it is a node-red bug (or at least deficiency) or if it is the browser confused by something silly in the profile data.  I need to find the time to do some more investigating, but it isn't actually a big issue for me at the moment as I don't have a need for the widget, I was investigating a problem for someone else when I noticed it.

**Comment by dhamukrish** [comment]
I am also facing the same issue, basically, we need to refresh the browser every time to see the status when you switch over from another side-menu item.

**Comment by colinl** [comment]
This issue is that the led is *always* grey, whatever you do, but only in one instance so far.  If you can make it update the display be refreshing then it is not the same issue.

**Comment by yoiang** [comment]
@colinl If you have time to can you outline in detail the order exactly of what happens compared to the expected results to make sure it's understood what this issue is about? The @dhamukrish can decide if they need a separate issue created.

**Comment by colinl** [comment]
@yoiang I think perhaps you meant to address that to @dhamukrish.  This issue is quite clear, when the issue occurs the led stays grey always.  It does not show anything else whatever one does with refreshing or sending the node messages or whatever.
