### ISSUE TITLE
Custom LED size

### ISSUE THREAD

**Issue by yoiang** [Adorkable/node-red-contrib-ui-led#17]
Great idea suggested by @Nokomis449 in #3 

I imagine it would be a single pixel size or optionally a different width and height pixel size (have to make sure this actually looks good with our current LED).

My instinct is to keep the text at the default text size but should it grow to fill the height?

**Comment by juggledad** [comment]
+1 for this - or allow the size to be changed in CSS.

**Comment by yoiang** [comment]
Thinking through some options:
* option to have the LED autosize to fit height
  * if disabled can manually select height up to enclosed size if I can get at that, otherwise just 1
* @mschuricht feels the LED is too big (#57) compared to the text, potentially option to match text height

**Comment by yoiang** [comment]
Automatic resizing to fit height just added to the `develop` branch here: https://github.com/Adorkable/node-red-contrib-ui-led/commit/44b53a5f324ea49938f7b130852387e74c4d7bdf

<img width="320" alt="Screen Shot 2021-01-13 at 1 32 07 PM" src="https://user-images.githubusercontent.com/89718/104512978-f9e9e500-55bc-11eb-8aa4-d9b85b80ecef.png">

Gonna close this when it's merged into the main branch but if people have ideas about sizing beyond automatic or if for some other reason this doesn't seem like a fit please say so here!
