### ISSUE TITLE
Left label margin should match right LED margin (margin for glow)

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#18]
There is the option for the "name" of the LED.
This means (for instance) if you make it 3 wide......   It would be nice to control where/how the text is shown.
"Left justified", "Centered", or "Right format".
Maybe not having the LED so close to the edge?  (See attached picture.  Note red line.)
And maybe even the option to put the text AFTER the LED, rather than before.

![screenshot from 2019-02-06 21-09-20](https://user-images.githubusercontent.com/39888280/52334441-ceb2fe80-2a53-11e9-903c-83fd24110900.png)

**Comment by yoiang** [comment]
I like left, centered, and right text justification options as well as the option to have the text after the LED! I'm going to separate them out into different tasks.

Can you elaborate on your middle point, you feel the LED is too close to the border?

**Comment by Just-another-pleb** [comment]
I think I included a picture in the original post, but see attached anyway.

The text also is too close to the ends/edges of the box.

Looking at it now, the LED may be ok for distance, but if you look at the
(now modified) picture you can see how close the text is to the left side
of the "box".
This may be because the text is (probably) left justified.

**Comment by yoiang** [comment]
Oh you meant match the distance of the text from the edge with the distance of the LED from the edge or vice versa? I'll play with how that would look when I have a sec!

**Comment by Just-another-pleb** [comment]
Well, something like that.

Just that when there is text, it doesn't look nice if the text is (say) 2
pixels in from the left edge and the LED is (say) 10.

I've forgotten what the LED by itself looks like in a 1 x 1 cell.

I just tried that, and it is too early I think.   But any way, I hope you
get the idea of what I am saying.

**Comment by yoiang** [comment]
RE: title change, this issue represents the last part of the 3 requests @Just-another-pleb made above:

Per they're image the LED's right margin is larger than the label's left margin, and it would likely look better if they matched!

Either the LED's glow should overhang the right side of the container and the actual LED should be as close as the label or the label should moved in to match the LED's spacing.

**Comment by yoiang** [comment]
The former isn't possible without messing with styling higher up so fb27b9a8ceaf9266d223d8230371c7c8afcc7ad6 implements the latter (name matching LED's spacing)
