### ISSUE TITLE
Can't order layout position

### ISSUE THREAD

**Issue by agenteDserrano** [Adorkable/node-red-contrib-ui-led#19]
When change the position on the layout no changes on the UI.

**Comment by agenteDserrano** [comment]
I find the issue on file led.js
order: 0 must change for order: config.order


			if (checkConfig(config, node)) {
	            var done = ui.addWidget({
	                node: node,
	                format: HTML(config, ledStyleTemplate('gray')),
	                group: config.group,
	                templateScope: "local",
	                order: config.order,
	                beforeEmit: beforeEmit,
	                initController: initController
				});

**Comment by yoiang** [comment]
Good catch!

**Comment by yoiang** [comment]
I will close this once it has been included in the published version, thanks for your help!

**Comment by yoiang** [comment]
Pushed in [0.2.0](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.2.0)!
