### ISSUE TITLE
Label text alignment options

### ISSUE THREAD

**Issue by yoiang** [Adorkable/node-red-contrib-ui-led#21]
A way to specify the label text's alignment as _left_, _right_, or _center_

Suggested by @Just-another-pleb in #18

**Comment by Just-another-pleb** [comment]
Yes but comparing it to the `text` node from the dashboard:

(See picture)

It seems to have a few text formatting issues covered.

I'm not saying this is the "be all and end all" but only an option.

**Comment by yoiang** [comment]
Your post didn't come through with a picture, do you mean from #18?

**Comment by Just-another-pleb** [comment]
Which post?  The one I just sent or the one I added to the "issue"?

**Comment by Just-another-pleb** [comment]
Your post didn't come through with a picture, do you mean from #18
<https://github.com/Adorkable/node-red-contrib-ui-led/issues/18>?

Yes.

**Comment by yoiang** [comment]
Completed in b6b0720a94307ab1c68979fa27b48497fc62ebcc
