### ISSUE TITLE
Status of LED not stored in Node...Delay to display results

### ISSUE THREAD

**Issue by WombatHollow** [Adorkable/node-red-contrib-ui-led#24]
When you open the Node-Red HTML page with the UI on it, the LED(s) are grey as if there is no data even though the Node is getting message data regularly.   It is not until the next message is sent to the Node that the LED will illuminate.
*To Reproduce**
Steps to reproduce the behaviour:
1. setup a flow which sends a toggling data message to the node-red-contrib-ui-led Node, changing payload between different values (mine were 'Good', 'Slow' and 'Down' every 60 seconds).  Deploy.
2. Open the HTML page with the UI after approx 60 seconds all the LEDs will display the correct state, navigate to another page (without this LED UI), then navigate back to the UI page with the LED UI.  The LED will be grey until the next message arrives (up to 60 seconds). 

I would expect the LED to show the colour from the last message received by node before the HTML page is opened, not wait for next msg

**Screenshots**

**Desktop (please complete the following information):**
 - OS: W10 and Android 9
 - Browser: Chrome (on all OS) and IE 11
 - Version: latest

**Additional context**
NB this seperate to another problem reported separately where the LED stays grey even though it is getting messages which can display grey on some computers and properly on others.

**Comment by yoiang** [comment]
@WombatHollow can you share a flow that illustrates your setup?
