### ISSUE TITLE
Size of screen taken up by LED

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#28]
Ok, this is more a request than a bug.

When you create the LED on the dashboard, there is no means to edit the "size" that it takes up.

Explination:
Say I have a group which is  6 squares wide.
I have another node that is 3 squares wide in that group.
I want to put the LED on the same "line" (horizontal) as the a fore mentioned node.
Alas it can't be done.  There is no way to make the LED 3 squares wide, so the two can fit in the 6 wide group and not the LED is an entire line by itself.

Could it be added at some time to allow this?

Thanks.

**Comment by yoiang** [comment]
@Just-another-pleb Can you point me at an example or a screenshot of what you mean? Also can you point me at another UI node that allows you to specify its size? That would be super helpful, thank you!

**Comment by Just-another-pleb** [comment]
Ok,

See attached.

The "Group" is 6 wide.

I put your LED in it and a "switch".

The Switch is 3 wide - green rectangle.
The LED fills up the entire width of the group.

So I can put something else after the switch on the same "line".
But I can't edit the LED properties to allow this.

Also if the width is ......   12 (or something) the label and the LED would
be a long way apart.

Clearer?

**Comment by yoiang** [comment]
@Just-another-pleb the attached didn't come through unfortunately, could you try again?

**Comment by Just-another-pleb** [comment]
Standbye.   I'll try via Github.

**Comment by Hypnos3** [comment]
For other UI elements (like a switch) there is a size selection:
![image](https://user-images.githubusercontent.com/12692680/55433098-ee1e6180-5594-11e9-8415-f4321dcbc652.png)

The LES does not have such a selection:
![image](https://user-images.githubusercontent.com/12692680/55433165-10b07a80-5595-11e9-8cc6-9049a806802f.png)

when you push this you can select how many space the ui element takes:
![image](https://user-images.githubusercontent.com/12692680/55433204-245be100-5595-11e9-9cd5-0a24f9aecf25.png)

**Comment by yoiang** [comment]
Perfect, I'll check it out tonight. Thanks for pointing me in the right direction!

**Comment by Just-another-pleb** [comment]
Ok, here I go again.

Let's hope this works this time.

Ok, I can't find how to attach things here.

But it seems Hypnos3 has hit it on the head.

Oh, just saw how to attach.

Refer back to my previous post.

![Screenshot from 2019-04-03 07-02-44](https://user-images.githubusercontent.com/39888280/55433366-f56b5c80-55e0-11e9-9f47-87849a20b3c7.png)
![Screenshot from 2019-04-03 07-02-49](https://user-images.githubusercontent.com/39888280/55433370-f56b5c80-55e0-11e9-8d3d-f4e4f95498c3.png)

**Comment by yoiang** [comment]
Available in 6c0832e3cf608d04d2a47fd1ba4441ca33f44bc0
Follow the milestone to know when it's been released
