### ISSUE TITLE
Left border overlap glow

### ISSUE THREAD

**Issue by Cyb3rn0id** [Adorkable/node-red-contrib-ui-led#33]
On all my devices, glow on the left side of the led is covered by the invisible border: maybe glow is too large or led is not centered in the box? I've this artifact whatever is the size of the widget.
Normally I use a widget size of 1x1 for the led with no label since the led is near a button and I've used yellow color instead of green for the 'true' value.

![left_glow](https://user-images.githubusercontent.com/9216461/57443851-3fcea180-724f-11e9-9818-89cb31dd14c1.png)

Nodered 0.19.4 running on Raspbian
browser: chrome on Windows and Android

**Comment by Cyb3rn0id** [comment]
I've taken another screenshot giving the group border and group background a red color for highlighting them. As you can see maybe the problem is given by a not perfect centered image in the 1x1 widget box.

![led_glow](https://user-images.githubusercontent.com/9216461/57444376-51647900-7250-11e9-9deb-b9e6a9588bc2.png)

**Comment by yoiang** [comment]
Good catch, I'll see if I can repro it, thank you for reporting it!

**Comment by yoiang** [comment]
Fix released in https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.4.6
