### ISSUE TITLE
LEDs not always changing when sent signals.

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#35]
This is still not 100% proven to be a bug with the LED node, but when I inject a message which tells the LED to turn a certain colour and it doesn't.......

This is happening on a few flows, now and then.
A signal which is set in the LED node is sent and it simply doesn't change colour.

Out of curiosity I made a large flow with a lot of LEDs on it all different colours.
The colours were names (green, navy, cyan, etc) rather than RGB values.
So I could easily pick a colour for a LED if/when I wanted on.

It is one `inject` node with the `inject at start` set to 5 seconds.
Some times (on boot) the screen is all grey LEDs.
Now, with further testing even manually pressing the INJECT node, the LEDs don't change colour from GREY.

NR 0.20.5
LED 0.2.3
FF and Chrome tests fail.
Chrome pretty well virgin: no addons.

Flow available in/on node-red library.
Link:[https://flows.nodered.org/flow/7a2337014a09018eb7f14c9a93237997

It would be nice to work out what is going on.

![Screenshot from 2019-06-19 13-05-23](https://user-images.githubusercontent.com/39888280/59733938-ec5e6300-9292-11e9-8be4-8983879a1fc8.png)

**Comment by juggledad** [comment]
Your flow doesn't work because you have nothing set in the button's **When clicked, send:** payload. If that is not set, the button node sends the node ID which is not a boolean tryue or false.

**Comment by Just-another-pleb** [comment]
Yeah, I am sorry.

I have recently been caught up in a lot of messy stuff with the computer, internet and a whole lot of other stuff.
(Yeah, I know.   No excuse.)

I was caught out with reading how the button says "if input received, send to output".
That isn't exactly correct.  It sends what it has as its "when pressed" message.

I seem to be parsing a lot of things incorrectly recently.

Greatest apologies.   I don't like "crying wolf".
