### ISSUE TITLE
Does not show in the dashboard in Node Red running as root

### ISSUE THREAD

**Issue by Cyb3rn0id** [Adorkable/node-red-contrib-ui-led#37]
I modified nodered.service to be able to run Node Red as root. After I restarted Node Red I had to reinstall Dashboard, LED node and then re-imported the flows. Now The Led not showing.

**Comment by yoiang** [comment]
Hey @Cyb3rn0id , is your configuration anything like #8?

**Comment by yoiang** [comment]
If you have any information to share please do, closing for now!
