### ISSUE TITLE
Insert color

### ISSUE THREAD

**Issue by luqmanredin** [Adorkable/node-red-contrib-ui-led#45]
**Describe the bug**
I could not insert the color in the color selection

**Screenshots**

![image](https://user-images.githubusercontent.com/53413259/66537872-a33d6200-eb54-11e9-85ad-fc2f671ee85a.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by yoiang** [comment]
Hello @luqmanredin , thank you for reporting this!
Do you know what version of Node-RED and Node-RED Dashboard you're running?

**Comment by luqmanredin** [comment]
My Node-RED version is v0.16.2 and Node-RED Dashboard v2.13.0

**Comment by luqmanredin** [comment]
My Node-RED version is v0.16.2 and my Node-RED Dashboard is v2.17.1

**Comment by yoiang** [comment]
I am unable to reproduce the issue short of reverting to this version of Node-RED, would you mind some hands on debugging before I jump in?

Can you open up the Chrome Developer console, click on the + Color button, and see if there is an error message there or in the Node-RED console?

**Comment by luqmanredin** [comment]
The error message when I click on the + Color button as per image below;
![image](https://user-images.githubusercontent.com/53413259/66724851-5eb80c00-ee5d-11e9-9b7a-52f7801823b4.png)

**Comment by yoiang** [comment]
Hello @luqmanredin !
I apologize for the very very late reply, are you still having issues?

**Comment by yoiang** [comment]
I haven't been able to replicate or heard back, closing old issue
