### ISSUE TITLE
Dashboard version message when removing nodes.

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#47]
When updating nodes I got this message after a node was removed:

```
node-red-contrib-ui-led@0.3.1 requires a peer of node-red-dashboard@2.14.x but none is installed. You must install peer dependencies yourself.
```

Thing is the dashboard installed is 2.19.2

That is greater than 2.14.x

Is this a problem?

**Comment by Just-another-pleb** [comment]
Sorry....    Stuff learned since, it is not your problem.

**Comment by ozett** [comment]
i observed the sam message today.
what do i have to do? nothing? update?

greatly appreciate any hints...something to do about this?
