### ISSUE TITLE
Multiple LEDs on the same workspace

### ISSUE THREAD

**Issue by TadyTheFish** [Adorkable/node-red-contrib-ui-led#50]
Hello.
I tried  to put a few leds on a tab but I'm having problems.
It seems if you put a few leds and position them and then if you try to rearrange after you deploy thre is a good chance that the whole layout is randomly changed.
Could this have anything to do with the fact that you can't change the name of the led in a flow (also causes big problems identifying the leds)

**Comment by yoiang** [comment]
Hello @TadyTheFish !
I apologize for the very late reply, can you export the flow and paste it here? I'd be able to reproduce it locally.

Also can you clarify what you mean by not being able to change the name of the led in a flow? Do you mean the `Name` value? It might be scrolled below the fold in your Edit Properties window!

**Comment by yoiang** [comment]
I haven't heard back, closing old issue
