### ISSUE TITLE
Contrib doesn't work on latest version of Node?

### ISSUE THREAD

**Issue by lancelon** [Adorkable/node-red-contrib-ui-led#52]
This contrib doesn't seem to work on the latest version of nodejs - is that true? Seems to only work on v10.16.3

**Comment by yoiang** [comment]
Hello @lancelon ! 
Sorry for the late reply! Can you give more information into your setup (Node, Node-RED, Node-RED Dashboard, global or local installs, etc). I have tested against the current LTS (12.18.2 at time of writing) and things appear to be working a-ok!

**Comment by G0sch** [comment]
Hey :-)

Looks like is also do not work for me - tried the example from example folder

11 Aug 18:57:41 - [info] Node-RED version: v1.1.3
11 Aug 18:57:41 - [info] Node.js  version: v12.18.3
11 Aug 18:57:41 - [info] Linux 5.4.51-v7l+ arm LE
Tested in current Safari and Chrome on Mac

<img width="610" alt="Screen Shot 2017-03-24 at 22 06 03" src="https://user-images.githubusercontent.com/51472553/89926352-0d0b1a00-dc05-11ea-8067-f67130eb1e03.png">

Thx
G0sch

**Comment by yoiang** [comment]
Thanks for your patience @lancelon and @G0sch. I've just pushed a new rewritten version [0.4.2](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.4.2) using the latest node-red and node-red-dashboard. 

Let me know if this resolves the issue for you, if not can you see if there are any logs in the browser console or in the Node-RED console?

**Comment by yoiang** [comment]
Have not heard back, closing for now!
