### ISSUE TITLE
Node not displayed on dashboard

### ISSUE THREAD

**Issue by bergmanu** [Adorkable/node-red-contrib-ui-led#53]
With node-red V1.0.2 the LED nodes are not displayed on the dashboard.
This is from your [example](https://flows.nodered.org/node/node-red-contrib-ui-led-fork): 
![image](https://user-images.githubusercontent.com/22653568/87425594-36249480-c5de-11ea-80ad-fdc5ed5ee83f.png)

There should be a LED, right? 

Also using an own flow with these nodes, they are not displayed on the dashboard

**Comment by yoiang** [comment]
Hello @bergmanu !
Thanks for pointing this out, the example doesn't work with newer versions of Node, you may have gotten an error when you tried importing which may be why nothing is showing up. Instead I'd recommend importing from the examples included in the package. Let me know if this works!

**Comment by classic-audio** [comment]
I am in the same situation.
Imported to day using "Palette" - no error messages during import
No apperence on Dashboard.

**Comment by yoiang** [comment]
@classic-audio would you be able to paste in the json of your flow? I'll be able to reproduce it on my end that way!

**Comment by classic-audio** [comment]
This my code:
[{"id":"b5ebd50b.e47c68","type":"ui_led","z":"6ab13f46.9ff05","group":"e6f5d9e.4f6b128","order":3,"width":"1","height":"1","label":"","labelPlacement":"left","labelAlignment":"left","colorForValue":[{"color":"red","value":"false","valueType":"bool"},{"color":"green","value":"true","valueType":"bool"}],"allowColorForValueInMessage":false,"name":"On/Off","x":350,"y":340,"wires":[]},{"id":"e6f5d9e.4f6b128","type":"ui_group","z":"","name":"Kontor Sensorer","tab":"6f007e87.4673f","order":1,"disp":true,"width":"6","collapse":false},{"id":"6f007e87.4673f","type":"ui_tab","z":"","name":"Kontor","icon":"dashboard","disabled":false,"hidden":false}]


The Node-red vers:1.1.2

**Comment by bergmanu** [comment]
Hi @yoiang,
I think it does not depend on the example flow. This was just an example I pasted, because I thought you will better understand what I mean. 
I installed the nodes via Manage palette and also tried an own flow, but the behavior is the same. 

If you have no other dashboard node configured in your flow but only LED ones and open the dashboad, it claims that there is nothing configured. 

I hope you can reproduce with the flow from @classic-audio, I don't have anything running at the moment.

**Comment by southseaboy** [comment]
I'm seeing the same behaviour with a clean install of Node-RED v 1.1.2 (fresh x64 docker image), but am not getting problem with Node-RED v1.0.6 native on an RPi (32 bit Raspberry Pi OS).  When I deploy a flow containing the ui-led node on the docker version I see an error in the debug message list - "TypeError: Cannot read property 'length' of undefined".

**Comment by bergmanu** [comment]
I guess there was an update of the node, right?
I tried to install the node again today and now it works for me... 
I am not sure, but maybe I have used the ui-led-fork node last time and it didn't work because of that. 

@southseaboy: Do you have installed the dashboard? I forgot that at first and saw a similar error, but after installing the _node-red-dashboard_ and a reboot this was gone

**Comment by southseaboy** [comment]
I have version 0.3.3 installed via the manage palette menu this morning. I also had previously installed the standard dashboard nodes and configured a dashboard which is showing data from another flow. I get the error whether I try to put the node in en existing (displayed) ui_group or a new tab/group.

**Comment by bergmanu** [comment]
My versions are: 
Node JS: **10.15.2**
node-red: **1.0.2**
node-red-contrib-ui-led: **0.3.3**
node-red-dashboard: **2.23.0**

I am running an Isar built Debian 10 on Siemens IOT2050.

**Comment by southseaboy** [comment]
@bergmanu - the problematic docker version is on node.js 10.21.0.

If you're now happy that the 0.3.3 version of the node fixes your issue with the 1.0.2 version of Node-RED perhaps you should close this issue to avoid confusing @yolang over which are the affected versions. I can raise another issue, or hop on #52 which is similar and awaiting clarification from the issue raiser.

**Comment by bergmanu** [comment]
Sure, I am happy with that. 
I thought I'd let it open, because you are still having problems. I'll close it then. 
Thanks!
