### ISSUE TITLE
So what is the difference between ui-led and ui-led-fork?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [Adorkable/node-red-contrib-ui-led#54]
So what is the difference between ui-led and ui-led-fork?

**Comment by yoiang** [comment]
Haha I don't know! This might be the wrong of the two repos to ask this question ;)

**Comment by yoiang** [comment]
@Nodi-Rubrum if you don't have any concern or issues here I'm going to close this Issue

**Comment by Nodi-Rubrum** [comment]
Sure.  No problem.
