### ISSUE TITLE
Add ability to toggle glow effect around LED on and off from config panel

### ISSUE THREAD

**Issue by AndreasHeine** [Adorkable/node-red-contrib-ui-led#55]
> 22 Sep 09:33:59 - [info] Node-RED version: v1.1.3
> 22 Sep 09:33:59 - [info] Node.js  version: v12.18.3
> 22 Sep 09:33:59 - [info] Windows_NT 10.0.18363 x64 LE

![Unbenannt4](https://user-images.githubusercontent.com/56362817/93857759-61e98800-fcbb-11ea-9ea6-fe57c5f08e5d.PNG)

![Unbenannt](https://user-images.githubusercontent.com/56362817/93855811-6a8c8f00-fcb8-11ea-98f3-c5477fa3b4d6.PNG)

if i inject a msg.glow = false the glow is still there!?

![Unbenannt1](https://user-images.githubusercontent.com/56362817/93855979-ac1d3a00-fcb8-11ea-9d9c-374931b1571a.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/56362817/93856228-fbfc0100-fcb8-11ea-89ac-ba9cbda3a882.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/56362817/93856287-18983900-fcb9-11ea-8101-ccd9bd20c618.PNG)

**Comment by AndreasHeine** [comment]
if set 
```js
const glow = false; //msg.glow;
```
glow is gone ...

**Comment by yoiang** [comment]
Hello @AndreasHeine !
To clarify is injecting a `glow` **false** of **false** turning it off or is it still on?

Internally the control is passing `glow` amongst itself, and would overwrite values of `glow` someone sent further up the line. Perhaps the controls should internalize both the color and glow results in its own `payload`, hmmm!

**Comment by AndreasHeine** [comment]
injecting glow false does not turn the glow off!
yes color too - at least its similar code

**Comment by yoiang** [comment]
Gotcha! Would you have expected it to? If you read through the README documentation `glow` and `color` aren't expected `msg.payload` values. Can you explain your usage so I can understand better and we can consider what makes sense!

**Comment by AndreasHeine** [comment]
message object:
msg.payload
msg.glow
msg.color

i would expect that the led glow updates on message!? at least i tought thats what the code looks like (i might be wrong)

**Comment by yoiang** [comment]
That code is internal to the node, the `msg` with `glow` and `color` are processed from the payload it receives and sent between different parts of the node (part of the way Node-RED dashboard signals). The code isn't really a great way to learn how to use the node, the README is best!

[README](../blob/master/README.md)

**Comment by AndreasHeine** [comment]
if i look for example into the dashboard gauge its possible to change the sections on message same in some charts aswell. i normaly hardcode them off because i dont like the glow effect...

**Comment by zaubererty** [comment]
plus one

**Comment by yoiang** [comment]
So to clarify when you want to independent of the `msg.payload` value toggle the glow effect do you mean any coloration of the led or just the actual hazy glow around it?

**Comment by AndreasHeine** [comment]
both color and glow would be a awesome features!


#### dashboard gauge node:
if you want to change the colors of the sectors you can send a msg with a ui_contorl obj and empty payload obj to adjust the colors dynamic according to a setpoint
```js
let upper = msg.payload * 1.04;
let lower = msg.payload * 0.95;

msg = {};
msg.ui_control = {seg1:lower||0,seg2:upper||0}
return msg;
```

![Unbenannt](https://user-images.githubusercontent.com/56362817/95422786-3a8fed80-0940-11eb-9d77-a65e38f69566.PNG)

**Comment by yoiang** [comment]
Gotcha! I'm going to rename the issue accordingly for the glow, that would be new functionality.

Have you had a chance to read the documentation re: color definitions in the message (vs the default in the config panel): https://github.com/Adorkable/node-red-contrib-ui-led/blob/master/README.md#custom-statuses-in-msg . Let me know if that isn't enough, if there is some functionality regarding the colors that you don't think is covered here.

**Comment by yoiang** [comment]
The ability to disable the glow effect has been added to the node config panel in version [0.4.4](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.4.4)!

Created a separate issue for toggling from `msg`.
