### ISSUE TITLE
Set the size of the Led Circle

### ISSUE THREAD

**Issue by mschuricht** [Adorkable/node-red-contrib-ui-led#57]
The size of the LED is too powerful compared to the label. An adjustment of the size would be desirable.
![image](https://user-images.githubusercontent.com/74533447/99231673-3a152d00-27f1-11eb-827c-16d63d5eaf40.png)

**Comment by yoiang** [comment]
Forms of this request are happening more and more often, it will likely come in the next version!

**Comment by yoiang** [comment]
Realized this is a duplicate of #17, closing to consolidate
