### ISSUE TITLE
LED / Label not appearing on dashboard

### ISSUE THREAD

**Issue by josef62** [Adorkable/node-red-contrib-ui-led#59]
LED / Label not appearing on dashboard

In NR editor no problem to define, but nothing is showing up on dashboard. Space where it should be gets filled up with other following dashboard elements. All other dashboard elements working fine.

Raspi Linux 5.4.72-v7+ armv7l

**Versions**
 - node-red-contrib-ui-led: 0.3.3
 - node-red: 1.0.6
 - node-red-dashboard: 2.24.1

In previous versions doing well

**Comment by yoiang** [comment]
Hey @josef62 !
I've just pushed a new rewritten version [0.4.1](https://github.com/Adorkable/node-red-contrib-ui-led/releases/tag/0.4.1) using the latest node-red and node-red-dashboard. 

Let me know if this resolves the issue for you, if not can you see if there are any logs in the browser console or in the Node-RED console?

**Comment by yoiang** [comment]
Please feel free to comment here if this is still an issue, closing for now!
