### ISSUE TITLE
Save state of LED?

### ISSUE THREAD

**Issue by TheFoxy** [Adorkable/node-red-contrib-ui-led#66]
If i change between two Flows at the  UI the last state is gone. 
LED show always gray.
Can i change this?

**Comment by yoiang** [comment]
Hmm, this was an issue that should have been fixed a while ago, going to see if I an reproduce it on my end. In the future it would be helpful to know what version of **ui-led**, **node-red**, and **node-red-dashboard** you are using, do you have those on hand?

**Comment by SMerrony** [comment]
I'm seeing this too since the last (one or two) updates.  Everything is current: Node-Red 1.2.6, Dashboard 2.26.2, UI_LED 0.4.4.

**Comment by yoiang** [comment]
Apologies! Figured out the issue, was an error that came about in the rewrite. I've just pushed 0.4.5, give that a try!

**Comment by SMerrony** [comment]
That was quick - thanks.   A quick test in development looks good, will try it on production tomorrow.

**Comment by yoiang** [comment]
Keep me posted, sorry about that!

**Comment by connermacleod69** [comment]
Hi,
I have the same problem. But after updating manually it works again. Regards. Serge

**Comment by SMerrony** [comment]
All good - thanks for the widget and the quick fix.

**Comment by yoiang** [comment]
Great @SMerrony and @connermacleod69 , thank you for the follow up!
