### ISSUE TITLE
"Add Colour" Button not working

### ISSUE THREAD

**Issue by nksky** [Adorkable/node-red-contrib-ui-led#67]
**Describe the bug**
I recently upgraded to 0.4.6. The add colour button on the node in Node-red is not working

**To Reproduce**

1. ... Open Node Red
2. ... Drag Node to Flow, open try add extra colour.

**Expected behavior**
Ability to add more than 2 possible outcomes.

**Versions**

- node-red-contrib-ui-led: 0.4.6
- node-red: 1.1.2
- node-red-dashboard: 2.27.0

**Platform**

- OS: DietPi
- Browser Chrome

**Comment by glad-wolf** [comment]
Same here

- node-red-contrib-ui-led: 0.4.6
- node-red: 1.2.6 (runs in docker)
- node-red-dashboard: 2.26.2

**Comment by yoiang** [comment]
Thank you for reporting this, I'll try to repro tonight!

**Comment by kuema** [comment]
I can reproduce it as well.

The following error is shown in the browser's console.

![image](https://user-images.githubusercontent.com/13005915/105954334-d28f1f80-6074-11eb-83e9-4dd7a3d4650c.png)

**Comment by Zodiac-69** [comment]
Can we roll back to a previous version while you resolve this issue?

**Comment by yoiang** [comment]
Just pushed 0.4.7, please test that this resolves the issue for you, my apologies!

**Comment by glad-wolf** [comment]
Works for me.

It's a great plugin!
Thank you!

**Comment by yoiang** [comment]
I have heard back any other follow ups so I'm going to assume this has been resolved
