### ISSUE TITLE
Changing from fixed size back to auto messes up LED size

### ISSUE THREAD

**Issue by yoiang** [Adorkable/node-red-contrib-ui-led#68]
Reported by **kuema** here: https://discourse.nodered.org/t/announce-node-red-contrib-ui-led-0-4-6/39472/3

**Describe the bug**
Size of LED grows to incorrect size if going from fixed size to auto size

**To Reproduce**
1. Add an LED set to `auto`
2. Change size to a fixed on, say `1x1`
3. Close **Edit panel**
4. Change size back to `auto`
5. Close **Edit panel**
6. Deploy

**Expected behavior**
Should return to `auto` size

**Screenshots**
![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/d/7/d7c09a049b6ac5013da88f446150d6e3fe52d280.png)

From the flow, looks like width and height are being saved as `strings`
![](https://aws1.discourse-cdn.com/business6/uploads/nodered/original/3X/8/c/8c5c4dec9b0c854a169538e8dd973723200787ab.png)

**Versions**

- node-red-contrib-ui-led: 0.4.6

**Comment by kuema** [comment]
I did a little digging, too. 🤓 

It seems only the initial values are numbers. As soon as you change the size in any way, they end up as strings as well, like `"width": "1"`. So this might be a general Dashboard thing.

The problem is this strict comparison.

https://github.com/Adorkable/node-red-contrib-ui-led/blob/15f73cc411a93ea2b31cf98a5024a22e1d55eaa0/src/nodes/ui_led/ui_led.html/processing.ts#L34

So, one can either use `==` or convert the width to a number first.

**Comment by bburkett52** [comment]
I am seeing another issue that may be related to this issue.
When displayed on my iPhone, in portrait orientation, the LED initially shows as a thin vertical slit.
If I rotate the device 90 degrees, to landscape mode, the LED displays properly and then even when rotated back to portrait mode.
This anomaly began with the 0.4.7 version.

![62195](https://user-images.githubusercontent.com/35471928/106692684-ee2d8500-65a2-11eb-93c3-6d78df779342.jpg)

Regards,
Bob

**Comment by yoiang** [comment]
I have addressed the issue @kuema you and others had run into with 0.4.8, please let me know if you have any issues!

@bburkett52 let me take some time to reproduce the issue, if it's still happening I'll make a new issue. Thanks so much for  reporting it :)

**Comment by bburkett52** [comment]
@yoiang,

Thanks you for your work! 
I have updated to version 0.4.8 and still have the same issue on my phone. 
All is good on on larger displays.

Regards,
Bob

**Comment by yoiang** [comment]
@bburkett52 please track progress on the issue you're seeing #72 !
