### ISSUE TITLE
Confusing name?

### ISSUE THREAD

**Issue by yoiang** [Adorkable/node-red-contrib-ui-led#7]
Will the name LED/led confuse folks and situations where flows signal actual leds?

**Comment by juggledad** [comment]
The fact that it has **ui** in it's name and it is in the dashboard part of the nodes palette and that most physical LED's are attached to a GPIO pin and so use a GPIO node, should be enough in my mind.

**Comment by dceejay** [comment]
I agree with @juggledad - the name is fine. 
this issue can be closed :-)

**Comment by yoiang** [comment]
Thanks for the feedback @juggledad and @dceejay ! If someone feels otherwise they're more than welcome to chime in, closing for now :)
