### ISSUE TITLE
Revise to avoid peer warning messages?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [Adorkable/node-red-contrib-ui-led#73]
Revise to avoid peer warning messages?  For example...
`npm WARN node-red-contrib-ui-led@0.4.4 requires a peer of node-red@^1.2.6 but none is installed. You must install peer dependencies yourself.`

**Comment by yoiang** [comment]
Are you getting this when you install via the Node-RED palette?

**Comment by Nodi-Rubrum** [comment]
Nope, when I install via npm cli.

**Comment by randomhammer** [comment]
This looks similar to the error I just opened (#84) that is preventing me from installing the widget from the palette. In my case the peer it is looking for is node-red-dashboard@2.23.2.

**Comment by yoiang** [comment]
Hello @Nodi-Rubrum , `node-red` is no longer marked as a peer dependency so you should not see the message in future versions!

Hello @randomhammer , this as been resolved in PR #87, released in version 0.4.10, tracked in #86 . Please let me know there if that resolves the issue!
